# -*- coding: utf-8 -*-
"""haberman.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LdaCxTplu4zACcnUNcIxQRbbtKcnYGsm
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('haberman.csv')
df.head()

"""The dataset contains cases from a study that was conducted between 1958 and 1970 at the University of Chicago's Billings Hospital on the survival of patients who had undergone surgery for breast cancer.

Attribute Information:

age- Age of patient at time of operation operation_year- Patient's year of operation axil_nodes- Number of positive axillary nodes detected status- Survival status 1 = the patient survived 5 years or longer 2 = the patient died within 5 year
"""

df.shape

df.describe()

df.info()

sns.heatmap(df.corr(numeric_only = True), annot=True)

df['status'].value_counts()

sns.countplot(x='status', data=df, hue='status',
              palette=['skyblue', 'lightcoral'], legend=False)

plt.show()

sns.displot(data=df, x="age", color="mediumpurple",
            kind="hist", kde=True, height=5, aspect=1)
plt.show()

sns.displot(data=df, x="age",hue= 'status',palette=["plum", "purple"],kind="hist",kde=True,height=5, aspect=1)

sns.displot(data=df, x="operation_year",hue='status', palette="bright",kind="hist",kde=True,height=5, aspect=1)

df['axil_nodes'].unique()

df['axil_nodes'].value_counts()

plt.figure(figsize=(10,5))
sns.countplot(x='axil_nodes',data=df)

plt.figure(figsize=(15,5))
sns.countplot(x='axil_nodes',hue='status',data=df)